
---
- name: Install NTP
  shell: tdnf -y install ntp

- name: Configure the ntp time servers
  template:
    src: templates/ntp-conf.j2
    dest: /etc/ntp.conf
  run_once: true

- name: Enable NTP
  shell: systemctl enable ntpd
  
- name: Start NTP
  shell: systemctl start ntpd

- name: Ensure network time sync is setup
  shell: timedatectl set-ntp true

- name: Verify NTP Sources
  shell: ntpq -p
  register: ntp_out

- debug: msg="{{ ntp_out.stdout_lines }}"
