#- name: generate custom Calico Node manifest
#  become: true
#  template:
#    src: templates/calico-node-3.3.j2
#    dest: /tmp/calico-node.yml

- name: download the current Calico Node default manifest
  shell: "curl -L -O https://docs.projectcalico.org/{{ k8s_calico_version }}/getting-started/kubernetes/installation/manifests/app-layer-policy/kubernetes-datastore/calico-networking/calico-node.yaml"
  args:
    chdir: /tmp
  register: calico_def_out
  
- debug: msg="{{ calico_def_out.stdout_lines }}"

- name: "update the manifest with the correct cluster CIDR: {{ k8s_cluster_cidr }}"
  shell: "sed 's/.*192.168.0.0.*/              value: \"{{ k8s_cluster_cidr | replace('/', '\\/') }}\"/' /tmp/calico-node.yaml > /tmp/calico-node-fixed.yaml"

- name: view modified Calico Node manifest
  shell: cat /tmp/calico-node-fixed.yaml
  register: calico_view_out
  
- debug: msg="{{ calico_view_out.stdout_lines }}"

- name: install Calico node manifest
  shell: kubectl apply -f /tmp/calico-node-fixed.yaml
  register: calico_out
  
- debug: msg="{{ calico_out.stdout_lines }}"

- name: wait for the Calico nodes to restart
  pause:
    minutes: 4

