- name: configure Canal CNI network plugin
  include: cni-canal.yml
  when: k8s_network_cni == "canal"

- name: configure Calico CNI network plugin
  include: cni-calico.yml
  when: k8s_network_cni == "calico" or k8s_network_cni == "calico-policy"

- name: configure Calico CNI Network Policy 
  include: cni-calico-policy.yml
  when: k8s_network_cni == "calico-policy"
